import React from "react";
import Tabla from "../componentes/Tabla";

const columnas = [
  { name: "Producto" },
  { name: "Lunes" },
  { name: "Martes" },
  { name: "Miércoles" },
  { name: "Jueves" },
  { name: "Viernes" },
  { name: "Sábado" },
  { name: "Domingo" },
  { name: "Total Semanal" },
];

const filas = [
  {
    Producto: "Pizza Hawaiana",
    Lunes: 4,
    Martes: 2,
    Miercoles: 4,
    Jueves: 8,
    Viernes: 10,
    Sabado: 11,
    Domingo: 16,
    totalSemanal: 0,
  },
  {
    Producto: "Calsone Mediano",
    Lunes: 6,
    Martes: 3,
    Miercoles: 5,
    Jueves: 9,
    Viernes: 11,
    Sabado: 12,
    Domingo: 17,
    totalSemanal: 0,
  },
  ,
  {
    Producto: "Frappé Chocolate",
    Lunes: 6,
    Martes: 3,
    Miercoles: 5,
    Jueves: 9,
    Viernes: 11,
    Sabado: 12,
    Domingo: 17,
    totalSemanal: 0,
  },
  ,
  {
    Producto: "Pizza Jamón y Queso",
    Lunes: 6,
    Martes: 3,
    Miercoles: 5,
    Jueves: 9,
    Viernes: 11,
    Sabado: 12,
    Domingo: 17,
    totalSemanal: 0,
  },
  ,
  {
    Producto: "Pizza Capitán América",
    Lunes: 6,
    Martes: 3,
    Miercoles: 5,
    Jueves: 9,
    Viernes: 11,
    Sabado: 12,
    Domingo: 17,
    totalSemanal: 0,
  },
  {
    Producto: "Frappé Fresa",
    Lunes: 6,
    Martes: 3,
    Miercoles: 5,
    Jueves: 9,
    Viernes: 11,
    Sabado: 12,
    Domingo: 17,
    totalSemanal: 0,
  },
  {
    Producto: "Pizza Hongos",
    Lunes: 6,
    Martes: 3,
    Miercoles: 5,
    Jueves: 9,
    Viernes: 11,
    Sabado: 12,
    Domingo: 17,
    totalSemanal: 0,
  },
  {
    Producto: "Calsone Pequeño",
    Lunes: 6,
    Martes: 3,
    Miercoles: 5,
    Jueves: 9,
    Viernes: 11,
    Sabado: 12,
    Domingo: 17,
    totalSemanal: 0,
  },
  {
    Producto: "Frappé Banano",
    Lunes: 6,
    Martes: 3,
    Miercoles: 5,
    Jueves: 9,
    Viernes: 11,
    Sabado: 12,
    Domingo: 17,
    totalSemanal: 0,
  },
];

export function TablaContenedor() {
  return <Tabla columnas={columnas} filas={filas} />;
}
